version: 2.1

orbs:
  cicd: alayacare/cicd@1

parameters:
  backend-docker-imagename:
    type: string
    default: flower-backend
  backend-path:
    type: string
    default: ""
  backend-docker-filename:
    type: string
    default: "Dockerfile"

workflows:
  ci-workflow:
    jobs:
      - cicd/build:
          name: build
          path: << pipeline.parameters.backend-path >>
          has-test-stage: false
          docker-imagename: <<pipeline.parameters.backend-docker-imagename>>
          docker-filename: <<pipeline.parameters.backend-docker-filename>>
          context:
            - aws-ecr
            - github-app
            - docker-hub
